name: flutter_application_1
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  # Add image_picker for image selection functionality
  image_picker: ^0.8.7+4

  # Add intl for date and time formatting
  intl: ^0.17.0

  pin_code_fields: ^8.0.1 # Updated version

  flutter_map: ^6.1.0

  latlong2: ^0.9.0
  google_maps_flutter: ^2.6.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  http: ^1.4.0
  app_links: ^3.4.1
  url_launcher: ^6.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package contains a set of recommended lints to encourage good coding practices.
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is included with your application.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/image/

  # Example of adding custom fonts (commented out)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
